export const legalKeywords = {
  primary: {
    corporate: [
      'corporate law firm india',
      'business law consultancy india',
      'company registration lawyer',
      'corporate compliance services',
      'mergers and acquisitions india',
      'private limited company registration',
      'llp registration india',
      'corporate restructuring legal',
      'foreign company registration india',
      'board meeting compliance',
      'company law consultant',
      'director liability india',
      'shareholder agreement lawyer',
      'company annual compliance',
      'corporate governance india',
    ],
    litigation: [
      'litigation lawyer india',
      'commercial dispute resolution',
      'civil litigation services',
      'legal representation india',
      'court case lawyer',
      'high court advocate',
      'supreme court lawyer india',
      'civil case lawyer',
      'criminal defense attorney',
      'consumer court lawyer',
      'arbitration lawyer india',
      'legal notice drafting',
      'court case status',
      'debt recovery tribunal lawyer',
      'nclat advocate',
    ],
    intellectual_property: [
      'intellectual property lawyer india',
      'patent registration india',
      'trademark attorney india',
      'copyright registration services',
      'ip protection law firm',
      'patent opposition india',
      'software patent lawyer',
      'trademark infringement case',
      'patent search india',
      'design registration lawyer',
      'ipr litigation services',
      'trade secret protection',
      'patent licensing india',
      'geographical indication registration',
      'ip portfolio management',
    ],
    real_estate: [
      'real estate lawyer india',
      'property law consultant',
      'rera compliance services',
      'real estate due diligence',
      'property documentation legal',
      'property title verification',
      'real estate agreement review',
      'land acquisition lawyer',
      'property dispute resolution',
      'building approval legal',
      'lease agreement lawyer',
      'property registration lawyer',
      'real estate litigation',
      'property tax consultant',
      'commercial property lawyer',
    ],
    family_law: [
      'divorce lawyer india',
      'child custody lawyer',
      'marriage registration',
      'family court advocate',
      'maintenance case lawyer',
      'domestic violence legal help',
      'mutual divorce procedure',
      'inheritance lawyer india',
      'will registration lawyer',
      'adoption legal services',
      'hindu marriage act lawyer',
      'muslim personal law expert',
      'family property dispute',
      'succession certificate',
      'guardianship lawyer',
      'divorce procedure india',
      'alimony lawyer india',
      'child support lawyer',
      'divorce mediation services',
      'contested divorce lawyer',
      'marriage counseling legal',
      'matrimonial dispute lawyer',
      'divorce settlement expert',
      'marriage annulment lawyer',
      'family court procedures',
    ],
  },
  secondary: {
    employment: [
      'employment lawyer india',
      'labor law compliance',
      'workplace legal consultant',
      'hr legal services india',
      'employment contract review',
    ],
    criminal: [
      'criminal lawyer india',
      'bail lawyer',
      'criminal defense attorney',
      'fir consultation lawyer',
      'criminal case advocate',
      'cybercrime lawyer india',
      'economic offenses lawyer',
      'criminal appeal lawyer',
      'anticipatory bail lawyer',
      'section 138 case lawyer',
      'criminal writ petition',
      'ncb case lawyer',
      'ed case lawyer',
      'cbi case lawyer',
      'criminal trial lawyer',
      'ndps act lawyer',
      'drug case lawyer india',
      'narcotic cases advocate',
      'serious crimes lawyer',
      'murder case advocate',
      'assault case lawyer',
      'criminal conspiracy lawyer',
      'pocso act lawyer',
      'gang related cases',
      'habeas corpus petition',
    ],
    constitutional: [
      'constitutional lawyer india',
      'fundamental rights case',
      'pil filing lawyer',
      'constitutional writ petition',
      'article 32 petition',
      'constitutional law expert',
      'supreme court constitution bench',
      'constitutional amendment lawyer',
      'right to equality case',
      'constitutional remedies india',
    ],
    cyber_law: [
      'cyber law expert india',
      'cybercrime lawyer',
      'online fraud legal help',
      'data protection lawyer',
      'it act compliance',
      'cyber defamation case',
      'digital evidence lawyer',
      'cryptocurrency legal india',
      'cyber security law',
      'social media legal issues',
      'cyber stalking lawyer',
      'online harassment cases',
      'data breach lawyer',
      'cyber extortion cases',
      'hacking case lawyer',
      'cyber forensics expert',
      'internet crime lawyer',
      'digital privacy lawyer',
      'cyber bullying cases',
      'online theft lawyer',
    ],
    banking_financial: [
      'banking lawyer india',
      'loan recovery lawyer',
      'sarfaesi act lawyer',
      'banking fraud case',
      'financial regulatory compliance',
      'rbi compliance lawyer',
      'sebi lawyer india',
      'insurance claim lawyer',
      'letters of credit legal',
      'bank guarantee dispute',
      'cheque bounce lawyer',
      'section 138 expert',
      'debt recovery expert',
      'negotiable instruments act',
      'banking disputes lawyer',
      'loan default cases',
      'financial fraud lawyer',
      'drt case expert',
      'loan restructuring lawyer',
      'banking ombudsman cases',
    ],
    property_law: [
      'property verification lawyer',
      'real estate title search',
      'property documentation check',
      'land records verification',
      'property encumbrance check',
      'real estate due diligence',
      'property ownership dispute',
      'ancestral property lawyer',
      'property mutation lawyer',
      'illegal construction lawyer',
      'property tax disputes',
      'property registration expert',
      'land acquisition cases',
      'property boundary dispute',
      'tenancy law expert',
    ],
  },
  specialized_practice: {
    ndps_law: [
      'ndps act lawyer india',
      'drug case lawyer',
      'ndps bail lawyer',
      'narcotic drugs lawyer',
      'psychotropic substances case',
      'drug trafficking defense',
      'ndps court trial lawyer',
      'drug possession defense',
      'ndps act section 37',
      'drug case defense attorney',
      'ncb raid lawyer',
      'drug seizure case',
      'ndps special court lawyer',
      'controlled substances lawyer',
      'international drug case lawyer',
    ],
    divorce_law: [
      'divorce attorney expert',
      'quick divorce lawyer',
      'contested divorce expert',
      'alimony rights lawyer',
      'child custody specialist',
      'divorce settlement expert',
      'marriage counseling lawyer',
      'divorce mediation expert',
      'divorce property division',
      'matrimonial dispute lawyer',
      'divorce court procedures',
      'marriage annulment lawyer',
      'maintenance rights expert',
      'divorce tax implications',
      'international divorce lawyer',
    ],
    cyber_crime: [
      'cybercrime expert lawyer',
      'online fraud attorney',
      'cyber stalking lawyer',
      'digital evidence expert',
      'cyber defamation case',
      'hacking case lawyer',
      'internet crime defense',
      'cyber extortion lawyer',
      'data theft attorney',
      'cyberbullying case',
      'online harassment lawyer',
      'crypto fraud lawyer',
      'ransomware attack legal',
      'social media crime lawyer',
      'cyber forensics expert',
    ],
    property_verification: [
      'property title verification',
      'legal property search',
      'property due diligence',
      'land records verification',
      'property ownership check',
      'encumbrance certificate',
      'property documents review',
      'real estate title search',
      'property chain of title',
      'legal property survey',
      'property liens search',
      'land mutation verification',
      'property registration check',
      'real estate legal audit',
      'property title insurance',
    ],
    cheque_bounce: [
      'cheque bounce lawyer',
      'section 138 expert',
      'negotiable instruments act',
      'dishonoured cheque case',
      'cheque return notice',
      'banking offense lawyer',
      'cheque dishonor remedy',
      'criminal notice 138',
      'cheque protest lawyer',
      'payment default case',
      'cheque bounce settlement',
      'statutory notice 138',
      'cheque fraud lawyer',
      'quick cheque resolution',
      'banking court expert',
    ],
    loan_matters: [
      'loan recovery lawyer',
      'debt resolution expert',
      'bank loan default case',
      'loan restructuring lawyer',
      'personal loan dispute',
      'business loan default',
      'loan agreement review',
      'mortgage dispute lawyer',
      'loan settlement expert',
      'banking fraud case',
      'loan modification lawyer',
      'debt collection defense',
      'loan enforcement case',
      'credit card debt lawyer',
      'loan harassment relief',
    ],
    expert_attorneys: [
      'senior advocate india',
      'specialized legal expert',
      'top criminal lawyer',
      'best civil attorney',
      'expert divorce lawyer',
      'corporate law specialist',
      'high court senior counsel',
      'supreme court expert',
      'banking law authority',
      'property law specialist',
      'cyber law expert',
      'ndps case specialist',
      'loan matters expert',
      'commercial dispute expert',
      'international law expert',
    ],
  },
  case_types: {
    civil: [
      'property dispute',
      'breach of contract',
      'recovery suits',
      'injunction cases',
      'specific performance',
      'civil appeals',
      'execution petitions',
      'partition suits',
      'declaratory suits',
      'money recovery',
    ],
    criminal: [
      'ipc 420 case',
      'criminal conspiracy',
      'economic offenses',
      'white collar crimes',
      'bail matters',
      'criminal appeals',
      'revision petitions',
      'quashing petitions',
      'anticipatory bail',
      'regular bail',
    ],
    corporate: [
      'shareholders dispute',
      'director disputes',
      'oppression mismanagement',
      'winding up petition',
      'corporate insolvency',
      'merger acquisition',
      'corporate fraud',
      'company liquidation',
      'board disputes',
      'minority shareholders rights',
    ],
    specialized_criminal: [
      'ndps act cases',
      'drug possession case',
      'drug trafficking lawyer',
      'narcotics case defense',
      'controlled substances case',
      'commercial quantity ndps',
      'bail in ndps cases',
      'section 138 cases',
      'cheque dishonor lawyer',
      'negotiable instruments case',
      'financial fraud cases',
      'cyber fraud cases',
      'online scam lawyer',
      'digital evidence cases',
      'cryptocurrency fraud',
    ],
  },
  qualifiers: [
    'best',
    'top',
    'expert',
    'leading',
    'experienced',
    'professional',
    'specialized',
    'trusted',
  ],
  services: [
    'legal consultation',
    'legal advisory',
    'legal compliance',
    'legal documentation',
    'legal audit',
    'due diligence',
    'regulatory compliance',
    'legal research',
  ],
  industry_specific: {
    technology: [
      'startup legal services',
      'software agreement lawyer',
      'it company compliance',
      'technology contracts',
      'saas legal compliance',
    ],
    manufacturing: [
      'factory compliance legal',
      'industrial dispute lawyer',
      'manufacturing license',
      'factory act compliance',
      'industrial property lawyer',
    ],
    healthcare: [
      'hospital legal compliance',
      'medical negligence lawyer',
      'healthcare license india',
      'medical insurance claims',
      'hospital registration legal',
    ],
    education: [
      'education law india',
      'school compliance legal',
      'university registration',
      'education institution lawyer',
      'education regulatory compliance',
    ],
    ecommerce: [
      'ecommerce legal compliance',
      'online business lawyer',
      'marketplace legal',
      'ecommerce policy india',
      'online retail compliance',
    ],
  },
  compliance_types: [
    'company compliance',
    'labor law compliance',
    'environmental compliance',
    'tax compliance',
    'data privacy compliance',
    'industry specific compliance',
    'regulatory compliance',
    'statutory compliance',
    'legal compliance audit',
    'compliance training legal',
  ],
  locations: {
    metro_cities: [
      'law firm in delhi',
      'law firm in mumbai',
      'law firm in bengaluru',
      'law firm in chennai',
      'law firm in kolkata',
      'law firm in hyderabad',
      'law firm in pune',
      'law firm in ahmedabad',
      'law firm in chandigarh',
      'law firm in jaipur',
      'law firm in lucknow',
      'law firm in gurgaon',
      'law firm in noida',
      'law firm in surat',
      'law firm in vadodara',
    ],
    tier_two_cities: [
      'law firm in indore',
      'law firm in bhopal',
      'law firm in patna',
      'law firm in ranchi',
      'law firm in bhubaneswar',
      'law firm in guwahati',
      'law firm in imphal',
      'law firm in shillong',
      'law firm in agartala',
      'law firm in aizawl',
      'law firm in kohima',
      'law firm in itanagar',
      'law firm in gangtok',
      'law firm in dibrugarh',
      'law firm in jorhat',
    ],
    northeast_region: [
      'law firm in guwahati',
      'law firm in silchar',
      'law firm in tezpur',
      'law firm in nagaon',
      'law firm in barpeta',
      'law firm in nalbari',
      'law firm in goalpara',
      'law firm in kamrup',
      'law firm in dhubri',
      'law firm in baksa',
      'law firm in chirang',
      'law firm in darrang',
      'law firm in dhemaji',
      'law firm in golaghat',
      'law firm in hailakandi',
    ],
  },
  family_law_extended: {
    divorce_services: [
      'divorce lawyer in delhi',
      'divorce lawyer in mumbai',
      'divorce lawyer in bangalore',
      'divorce lawyer in chennai',
      'divorce lawyer in kolkata',
      'divorce lawyer in hyderabad',
      'divorce lawyer in pune',
      'best divorce lawyer india',
      'quick divorce services',
      'mutual consent divorce',
      'contested divorce expert',
      'divorce settlement lawyer',
      'divorce property division',
      'divorce alimony expert',
      'international divorce india',
    ],
    child_custody: [
      'child custody lawyer delhi',
      'child custody lawyer mumbai',
      'child custody rights india',
      'child support calculation',
      'custody battle lawyer',
      'joint custody lawyer',
      'sole custody expert',
      'child visitation rights',
      'interstate custody dispute',
      'international child custody',
      'child custody modification',
      'emergency custody order',
      'temporary custody lawyer',
      'custody evaluation expert',
      'child custody mediation',
    ],
    matrimonial_services: [
      'marriage registration lawyer',
      'prenuptial agreement india',
      'postnuptial agreement',
      'marriage counseling legal',
      'matrimonial dispute lawyer',
      'marriage annulment india',
      'court marriage lawyer',
      'interfaith marriage legal',
      'special marriage act',
      'marriage certificate legal',
      'matrimonial litigation',
      'marriage laws expert',
      'marriage property rights',
      'matrimonial remedies',
      'marriage dispute resolution',
    ],
    domestic_issues: [
      'domestic violence lawyer',
      'maintenance case expert',
      'alimony rights lawyer',
      'domestic abuse legal help',
      'protection order lawyer',
      'domestic violence act',
      'maintenance calculation',
      'interim maintenance',
      'domestic violence defense',
      'victim protection legal',
      'domestic harassment case',
      'family violence lawyer',
      'restraining order expert',
      'domestic dispute resolution',
      'emergency protection law',
    ],
  },
  criminal_law_extended: {
    general_criminal: [
      'criminal lawyer delhi',
      'criminal lawyer mumbai',
      'criminal lawyer bangalore',
      'criminal defense expert',
      'criminal case lawyer',
      'bail lawyer india',
      'criminal trial lawyer',
      'criminal appeal expert',
      'criminal defense strategy',
      'serious crimes lawyer',
      'criminal law specialist',
      'criminal court expert',
      'criminal investigation',
      'criminal procedure expert',
      'criminal defense counsel',
    ],
    specialized_crimes: [
      'white collar crime lawyer',
      'financial fraud expert',
      'cybercrime specialist',
      'drug offense lawyer',
      'economic crimes lawyer',
      'corporate fraud defense',
      'banking fraud lawyer',
      'securities fraud expert',
      'money laundering defense',
      'tax evasion lawyer',
      'corruption case expert',
      'embezzlement lawyer',
      'insider trading defense',
      'commercial crime lawyer',
      'criminal conspiracy expert',
    ],
  },
  generic_terms: [
    'law firm in india',
    'best law firm india',
    'top law firm india',
    'law firm near me',
    'legal services india',
    'legal consultancy india',
    'law office india',
    'law practice india',
    'legal advisors india',
    'indian law firm',
    'corporate law firm',
    'full service law firm',
    'business law firm',
    'commercial law firm',
    'litigation law firm',
  ],
  service_locations: [
    'law firm near me',
    'local law firm',
    'nearby lawyer',
    'legal services nearby',
    'law office location',
    'lawyer in my area',
    'local legal help',
    'nearest law firm',
    'local legal advisor',
    'legal consultant nearby',
    'closest law office',
    'neighborhood lawyer',
    'walk in legal consultation',
    'local attorney services',
    'same day legal help',
    'emergency lawyer nearby',
    'weekend lawyer appointment',
    '24 hour legal services',
    'immediate legal consultation',
    'legal help in locality',
    'law firm walking distance',
    'legal advisor near home',
    'local court lawyer',
    'district court attorney',
    'legal services in area',
    'lawyer office directions',
    'legal consultation nearby',
    'legal aid center location',
    'lawyer within 5km',
    'law chamber location',
    'nearest legal advisor',
    'local law chambers',
    'lawyers office near metro',
    'law firm near highway',
    'lawyer near residential area',
    'legal office downtown',
    'advocate chamber nearby',
    'legal consultant in vicinity',
    'lawyer near business district',
    'attorney office walking distance',
    'legal services near station',
    'lawyers near court complex',
    'legal help near market',
    'law firm near commercial area',
    'advocate near shopping center',
    'lawyer near hospital',
    'legal advisor near bank',
    'attorney near police station',
    'lawyer in city center',
    'legal office in business hub',
    'advocate in local market',
    'lawyer near university',
    'legal services near airport',
    'lawyer near industrial area',
    'advocate near tech park',
    'legal help near mall',
    'lawyer near government offices',
    'attorney near financial district',
    'legal advisor near bus station',
    'lawyer near residential colony',
    'advocate near township',
    'legal services near it park',
  ],
  bangalore_specific: {
    general_services: [
      'law firm in bangalore',
      'lawyer in bangalore',
      'advocate in bangalore',
      'legal services bangalore',
      'best lawyer bangalore',
      'top law firm bangalore',
      'legal consultation bangalore',
      'attorneys in bangalore',
      'law office bangalore',
      'legal advisor bangalore',
      'advocate office bangalore',
      'legal help bangalore',
      'legal expert bangalore',
      'law chamber bangalore',
      'legal consultant bangalore',
      'best advocate bangalore',
        'lawyers in bangalore',
        'legal firm bangalore',
    ],
    area_specific: [
      // Central Bangalore
      'lawyer in mg road',
      'advocate in brigade road',
      'law firm in church street',
      'lawyer in richmond road',
      'advocate in st marks road',
      'law firm in cunningham road',
      'lawyer in commercial street',
      'advocate in infantry road',
      'law firm in residency road',
      'lawyer in richmond town',
      'advocate in lavelle road',
      'law firm in vittal mallya road',
      'lawyer in ulsoor',
      'advocate in cox town',
      'law firm in frazer town',

      // East Bangalore
      'lawyer in indiranagar',
      'advocate in cv raman nagar',
      'law firm in old airport road',
      'lawyer in marathahalli',
      'advocate in whitefield',
      'law firm in mahadevapura',
      'lawyer in kr puram',
      'advocate in hoodi',
      'law firm in brookefield',
      'lawyer in kadugodi',
      'advocate in hope farm',
      'law firm in itpl',
      'lawyer in bagmane tech park',
      'advocate in kaggadasapura',
      'law firm in ramamurthy nagar',

      // South Bangalore
      'lawyer in koramangala',
      'advocate in hsr layout',
      'law firm in btm layout',
      'lawyer in jp nagar',
      'advocate in jayanagar',
      'law firm in banashankari',
      'lawyer in electronic city',
      'advocate in bommanahalli',
      'law firm in bannerghatta road',
      'lawyer in silk board',
      'advocate in bellandur',
      'law firm in sarjapur road',
      'lawyer in madiwala',
      'advocate in basavanagudi',
      'law firm in wilson garden',

      // North Bangalore
      'lawyer in hebbal',
      'advocate in malleshwaram',
      'law firm in sadashivanagar',
      'lawyer in rajajinagar',
      'advocate in yeshwanthpur',
      'law firm in nagawara',
      'lawyer in hennur',
      'advocate in kalyan nagar',
      'law firm in sanjaynagar',
      'lawyer in dollars colony',
      'advocate in rt nagar',
      'law firm in bel road',
      'lawyer in sahakarnagar',
      'advocate in yelahanka',
      'law firm in jakkur',

      // West Bangalore
      'lawyer in vijayanagar',
      'advocate in rajajinagar',
      'law firm in basaveshwaranagar',
      'lawyer in mahalakshmi layout',
      'advocate in nagarbhavi',
      'law firm in peenya',
      'lawyer in magadi road',
      'advocate in kamakshipalya',
      'law firm in rajajinagar industrial area',
      'lawyer in mysore road',
      'advocate in kengeri',
      'law firm in rr nagar',
      'lawyer in uttarahalli',
      'advocate in chandra layout',
      'law firm in chord road',

      // Tech Corridors
      'lawyer in manyata tech park',
      'advocate in global village tech park',
      'law firm in bagmane constellation',
      'lawyer in prestige tech park',
      'advocate in rmz infinity',
      'law firm in embassy tech village',
      'lawyer in embassy golf links',
      'advocate in outer ring road',
      'law firm in eco world',
      'lawyer in salarpuria softzone',
      'advocate in divyasree technopark',
      'law firm in vrr tech park',
      'lawyer in gopalan innovation mall',
      'advocate in global tech park',
      'law firm in cessna business park',

      // Business Districts
      'lawyer in diamond district',
      'advocate in world trade center',
      'law firm in ub city',
      'lawyer in orion mall',
      'advocate in phoenix marketcity',
      'law firm in forum mall',
      'lawyer in central mall',
      'advocate in brigade gateway',
      'law firm in mantri square',
      'lawyer in garuda mall',
      'advocate in bangalore central',
      'law firm in vr bengaluru',
      'lawyer in park square mall',
      'advocate in esteem mall',
      'law firm in elements mall'
    ],
    corporate_legal: [
      'corporate lawyer bangalore',
      'business lawyer bangalore',
      'startup lawyer bangalore',
      'company registration bangalore',
      'corporate law firm bangalore',
      'business compliance bangalore',
      'tech startup legal bangalore',
      'corporate attorney bangalore',
      'commercial lawyer bangalore',
      'business legal advisor bangalore',
      'company legal consultant',
      'corporate compliance bangalore',
      'startup legal services',
      'tech company lawyer',
      'business registration lawyer',
    ],
    property_legal: [
      'property lawyer bangalore',
      'real estate attorney bangalore',
      'land dispute lawyer bangalore',
      'property registration lawyer',
      'rera lawyer bangalore',
      'construction lawyer bangalore',
      'real estate legal services',
      'property document verification',
      'land title lawyer bangalore',
      'property tax lawyer',
      'real estate compliance',
      'building approval lawyer',
      'property litigation bangalore',
      'tenant dispute lawyer',
      'real estate due diligence',
    ],
    civil_matters: [
      'civil lawyer bangalore',
      'civil litigation bangalore',
      'civil case attorney',
      'civil court lawyer',
      'civil rights lawyer',
      'civil dispute resolution',
      'civil legal services',
      'contract lawyer bangalore',
      'consumer court lawyer',
      'civil law consultant',
      'civil court case',
      'civil appeal lawyer',
      'civil defense lawyer',
      'civil suit attorney',
      'civil legal advisor',
    ],
    criminal_defense: [
      'criminal lawyer bangalore',
      'criminal defense attorney',
      'criminal case lawyer',
      'bail lawyer bangalore',
      'criminal court lawyer',
      'criminal defense law firm',
      'criminal litigation lawyer',
      'criminal case advocate',
      'criminal defense counsel',
      'criminal law specialist',
      'criminal trial lawyer',
      'serious crimes lawyer',
      'criminal appeal lawyer',
      'cyber crime lawyer',
      'white collar crime lawyer',
    ],
    family_matters: [
      'divorce lawyer bangalore',
      'family court lawyer',
      'child custody lawyer',
      'marriage lawyer bangalore',
      'family law attorney',
      'divorce attorney bangalore',
      'matrimonial lawyer',
      'child support lawyer',
      'alimony lawyer bangalore',
      'marriage counseling lawyer',
      'family dispute lawyer',
      'divorce mediation bangalore',
      'child rights lawyer',
      'marriage registration lawyer',
      'family court advocate',
    ],
    startup_legal: [
      'startup lawyer bangalore',
      'tech startup legal',
      'startup compliance lawyer',
      'startup registration bangalore',
      'funding lawyer startup',
      'startup legal counsel',
      'tech company lawyer',
      'startup advisory legal',
      'esop lawyer bangalore',
      'startup contracts lawyer',
      'startup ip lawyer',
      'startup documentation legal',
      'startup compliance advisor',
      'tech legal services',
      'startup legal consultant',
    ],
    specialized_services: [
      'cyber law bangalore',
      'intellectual property lawyer',
      'patent lawyer bangalore',
      'trademark attorney',
      'employment lawyer bangalore',
      'tax lawyer bangalore',
      'immigration lawyer',
      'arbitration lawyer',
      'banking lawyer bangalore',
      'insurance lawyer',
      'medical negligence lawyer',
      'environmental lawyer',
      'education lawyer',
      'media entertainment lawyer',
      'blockchain crypto lawyer',
    ],
  },
};
