version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/shoolin.db
    volumes:
      - ./prisma/shoolin.db:/app/data/shoolin.db
      - ./public/uploads/media:/app/public/uploads/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
